### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Alperencode** [Alperencode/Algorithm-Solutions#1]
### Update README to provide a clear and concise description of the repository.

<br>

Optional:

- Add hyperlinks
- Reorganize the repository
- Add [folder structure](https://github.com/kriasoft/Folder-Structure-Conventions/blob/master/README.md#folder-structure-conventions)

**Comment by finn-str** [comment]
hey can you assign me this issue?

**Comment by Alperencode** [comment]
@finn-str
Of course, if you really want to.
